-- MySQL Script generated by MySQL Workbench
-- 04/06/16 10:23:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_frames
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_frames
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_frames` DEFAULT CHARACTER SET utf8 ;
USE `db_frames` ;

-- -----------------------------------------------------
-- Table `db_frames`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_frames`.`vehicles` (
  `idvehicle` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_vehicle` VARCHAR(45) NULL,
  `capacitance` INT NULL,
  `max_capacitance` INT NULL,
  `imei` DOUBLE NULL,
  `route` VARCHAR(45) NULL,
  PRIMARY KEY (`idvehicle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_frames`.`data_frame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_frames`.`data_frame` (
  `iddata_frame` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `up` INT NULL,
  `down` INT NULL,
  `onboard` INT NULL,
  `sensor_state` INT NULL,
  `error` INT NULL,
  `false_up` INT NULL,
  `false_down` INT NULL,
  `up_block` INT NULL,
  `down_block` INT NULL,
  `event_date` DATETIME NULL,
  `lat` FLOAT NULL,
  `lon` FLOAT NULL,
  `imei` DOUBLE NULL,
  `vehicle_idvehicle` DOUBLE NOT NULL,
  PRIMARY KEY (`iddata_frame`),
  INDEX `fk_data_frame_vehicles_idx` (`vehicle_idvehicle` ASC),
  CONSTRAINT `fk_data_frame_vehicles`
    FOREIGN KEY (`vehicle_idvehicle`)
    REFERENCES `db_frames`.`vehicles` (`idvehicle`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_frames`.`volatile_stop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_frames`.`volatile_stop` (
  `idvolatile_stop` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lat` FLOAT NULL,
  `lon` FLOAT NULL,
  `eventTime` DATETIME NULL,
  `vehicles_idvehicle` DOUBLE NOT NULL,
  PRIMARY KEY (`idvolatile_stop`),
  INDEX `fk_volatile_stop_vehicles1_idx` (`vehicles_idvehicle` ASC),
  CONSTRAINT `fk_volatile_stop_vehicles1`
    FOREIGN KEY (`vehicles_idvehicle`)
    REFERENCES `db_frames`.`vehicles` (`idvehicle`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_frames`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_frames`.`users` (
  `idusers` INT UNSIGNED NOT NULL,
  `name_user` VARCHAR(45) NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_frames`.`drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_frames`.`drivers` (
  `iddrivers` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_driver` VARCHAR(45) NULL,
  `active` TINYINT(1) NULL,
  `date_driver` DATETIME NULL,
  `users_idusers` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`iddrivers`),
  INDEX `fk_drivers_users1_idx` (`users_idusers` ASC),
  UNIQUE INDEX `name_driver_UNIQUE` (`name_driver` ASC),
  CONSTRAINT `fk_drivers_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `db_frames`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_frames`.`driver_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_frames`.`driver_events` (
  `iddriver_events` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vehicles_idvehicles` DOUBLE UNSIGNED NOT NULL,
  `drivers_iddrivers` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`iddriver_events`, `vehicles_idvehicles`, `drivers_iddrivers`),
  INDEX `fk_vehicles_has_drivers_drivers1_idx` (`drivers_iddrivers` ASC),
  INDEX `fk_vehicles_has_drivers_vehicles1_idx` (`vehicles_idvehicles` ASC),
  CONSTRAINT `fk_vehicles_has_drivers_vehicles1`
    FOREIGN KEY (`vehicles_idvehicles`)
    REFERENCES `db_frames`.`vehicles` (`idvehicle`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vehicles_has_drivers_drivers1`
    FOREIGN KEY (`drivers_iddrivers`)
    REFERENCES `db_frames`.`drivers` (`iddrivers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_frames`.`turn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_frames`.`turn` (
  `idturn_driver` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_turn` VARCHAR(45) NULL,
  `start_turn` TIME NULL,
  `end_turn` TIME NULL,
  `date_turn` DATETIME NULL,
  PRIMARY KEY (`idturn_driver`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_frames`.`driver_turn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_frames`.`driver_turn` (
  `drivers_iddrivers` INT UNSIGNED NOT NULL,
  `turn_idturn_driver` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`drivers_iddrivers`, `turn_idturn_driver`),
  INDEX `fk_drivers_has_turn_turn1_idx` (`turn_idturn_driver` ASC),
  INDEX `fk_drivers_has_turn_drivers1_idx` (`drivers_iddrivers` ASC),
  CONSTRAINT `fk_drivers_has_turn_drivers1`
    FOREIGN KEY (`drivers_iddrivers`)
    REFERENCES `db_frames`.`drivers` (`iddrivers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_drivers_has_turn_turn1`
    FOREIGN KEY (`turn_idturn_driver`)
    REFERENCES `db_frames`.`turn` (`idturn_driver`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
